FROM confluentinc/cp-kafka-connect:7.4.0

USER root

# MySQL JDBC 드라이버 다운로드  https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.11.tar.gz
RUN mkdir -p /usr/share/java \
  && mkdir -p /usr/share/java/kafka-connect-plugins \
  && chmod -R 755 /usr/share/java \
  && chmod -R 755 /usr/share/java/kafka-connect-plugins \
  && curl -L -o /usr/share/java/kafka-connect-plugins/mysql-connector-java.tar.gz https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-j-8.0.33.tar.gz \
  && tar -xvzf /usr/share/java/kafka-connect-plugins/mysql-connector-java.tar.gz --strip-components=1 -C /usr/share/java/kafka \
  && rm /usr/share/java/kafka-connect-plugins/mysql-connector-java.tar.gz


# Kafka Connect를 위한 설정 (필요시 추가)
#COPY connect-plugins /usr/share/java/kafka-connect-plugins

# 필요시 추가 환경 변수
#ENV CONNECT_PLUGIN_PATH=/usr/share/java/kafka-connect-plugins

# Kafka JDBC Sink Connector 다운로드
RUN curl -L -o /usr/share/java/kafka-connect-plugins/kafka-connect-jdbc.jar https://packages.confluent.io/maven/io/confluent/kafka-connect-jdbc/10.0.11/kafka-connect-jdbc-10.0.11.jar